FROM ghcr.io/linuxcontainers/debian-slim

LABEL org.opencontainers.image.authors="yasin.akar@vtcenerji.com"

ENV DOCKER_MODE=true
ENV NODE_ENV=production
ENV NODE_CONFIG_DIR=/app/conf
ENV LOG_FOLDER=/app/log

RUN addgroup \
        --system thingsboard \
        --gid 799 && \
    adduser \
        --system \
        --uid 799 \
        --ingroup thingsboard \
        --disabled-password \
        --no-create-home \
        --gecos "V-Sensor Application" \
        thingsboard
