ARG IMAGE_REPOSITORY
ARG IMAGE_VERSION

FROM $IMAGE_REPOSITORY/build:$IMAGE_VERSION AS build

FROM openjdk:8

COPY --from=build /src/msa/tb-node/target/thingsboard.deb /setup/thingsboard.deb
COPY --from=build /src/msa/transport/coap/target/tb-coap-transport.deb /setup/tb-coap-transport.deb
COPY --from=build /src/msa/transport/http/target/tb-http-transport.deb /setup/tb-http-transport.deb
COPY --from=build /src/msa/transport/mqtt/target/tb-mqtt-transport.deb /setup/tb-mqtt-transport.deb
COPY --from=build /src/msa/js-executor/target/tb-js-executor.deb /setup/tb-js-executor.deb
COPY --from=build /src/msa/web-ui/target/tb-web-ui.deb /setup/tb-web-ui.deb

RUN set -ex && \
    mkdir -p /usr/share/thingsboard

RUN dpkg -x /setup/thingsboard.deb /usr/share/thingsboard/core

RUN dpkg -x /setup/tb-coap-transport.deb /usr/share/thingsboard/coap

RUN dpkg -x /setup/tb-http-transport.deb /usr/share/thingsboard/http

RUN dpkg -x /setup/tb-mqtt-transport.deb /usr/share/thingsboard/mqtt

RUN dpkg -x /setup/tb-js-executor.deb /usr/share/thingsboard/js-executor

RUN dpkg -x /setup/tb-web-ui.deb /usr/share/thingsboard/web-ui

RUN ls -la /usr/share/thingsboard/js-executor

RUN ls -la /usr/share/thingsboard/js-executor/usr

RUN ls -la /usr/share/thingsboard/js-executor/usr/share

RUN chmod -R 555 /usr/share/thingsboard/core/usr/share/thingsboard/bin/thingsboard.jar

RUN chmod -R 555 /usr/share/thingsboard/mqtt/usr/share/tb-mqtt-transport/bin/tb-mqtt-transport.jar

RUN chmod -R 555 /usr/share/thingsboard/http/usr/share/tb-http-transport/bin/tb-http-transport.jar

RUN chmod -R 555 /usr/share/thingsboard/coap/usr/share/tb-coap-transport/bin/tb-coap-transport.jar

RUN chmod -R 555 /usr/share/thingsboard/js-executor/usr/share

RUN chmod -R 555 /usr/share/thingsboard/web-ui/usr/share

RUN ls -la /usr/share/thingsboard

RUN find / -iname "*executor"