ARG IMAGE_REPOSITORY
ARG IMAGE_VERSION

FROM $IMAGE_REPOSITORY/build:$IMAGE_VERSION AS build

FROM $IMAGE_REPOSITORY/base/js

ENV WEB_FOLDER=/app/web

COPY --from=build /usr/share/tb-web-ui/ /app/

COPY logback.xml /app/conf/logback.xml

RUN set -ex; \
    mkdir -p /app/log; \
    chown -R thingsboard:thingsboard /app; \
    chown -R thingsboard:thingsboard /tmp; \
    chmod a+x /app/bin/tb-web-ui

USER thingsboard

WORKDIR /app/bin

ENTRYPOINT ["/app/bin/tb-web-ui"]

CMD []
