ARG IMAGE_REPOSITORY
ARG IMAGE_VERSION

FROM $IMAGE_REPOSITORY/setup:$IMAGE_VERSION AS setup

ARG IMAGE_REPOSITORY

FROM $IMAGE_REPOSITORY/base

ARG THINGSBOARD_VERSION

LABEL maintainer="yasin.akar@vtc.com.tr"

ENV TB_VERSION=${THINGSBOARD_VERSION}
ENV DOCKER_MODE=true
ENV NODE_ENV=production
ENV NODE_CONFIG_DIR=/app/conf

COPY --from=setup /usr/share/tb-js-executor /app

COPY logback.xml /app/conf/logback.xml

USER thingsboard

WORKDIR /app/bin

ENTRYPOINT ["/app/bin/tb-js-executor"]

CMD []
