FROM eclipse-temurin:17-jre-alpine

RUN apk add --no-cache bash dos2unix

RUN addgroup \
        --system thingsboard \
        --gid 799 && \
    adduser \
        --system \
        --uid 799 \
        --ingroup thingsboard \
        --disabled-password \
        --no-create-home \
        --gecos "V-Sensor Application" \
        thingsboard
