name: Docker Image Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:

env:
  IMAGE_REGISTRY: docker.pkg.github.com
  IMAGE_REPOSITORY: valuabletouch/thingsboard-docker
  IMAGE_VERSION: build-${{ github.run_number }}
  THINGSBOARD_GIT_REPO: https://github.com/valuabletouch/thingsboard.git
  THINGSBOARD_GIT_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v2

    - name: Build 'thingsboard-base' Docker Image
      run: |
        docker build \
            --file Dockerfile.base \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-base \
            .

    - name: Build 'thingsboard-build' Docker Image
      run: |
        docker build \
            --file Dockerfile.build \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-build:$IMAGE_VERSION \
            --build-arg THINGSBOARD_GIT_REPO=$THINGSBOARD_GIT_REPO \
            --build-arg THINGSBOARD_GIT_BRANCH=$THINGSBOARD_GIT_BRANCH \
            .

    - name: Build 'thingsboard-node' Docker Image
      run: |
        docker build \
            --file Dockerfile.node \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-node:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'thingsboard-coap-transport' Docker Image
      run: |
        docker build \
            --file Dockerfile.coap-transport \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-coap-transport:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'thingsboard-http-transport' Docker Image
      run: |
        docker build \
            --file Dockerfile.http-transport \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-http-transport:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'thingsboard-mqtt-transport' Docker Image
      run: |
        docker build \
            --file Dockerfile.mqtt-transport \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-mqtt-transport:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'thingsboard-js-executor' Docker Image
      run: |
        docker build \
            --file Dockerfile.js-executor \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-js-executor:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'thingsboard-web-ui' Docker Image
      run: |
        docker build \
            --file Dockerfile.web-ui \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-web-ui:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Login to Docker Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u $GITHUB_ACTOR --password-stdin $IMAGE_REGISTRY

    - name: Push 'thingsboard-base' Image to Docker Registry
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-base:$IMAGE_VERSION

    - name: Push 'thingsboard-node' Image to Docker Registry
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-node:$IMAGE_VERSION

    - name: Push 'thingsboard-coap-transport' Image to Docker Registry
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-coap-transport:$IMAGE_VERSION

    - name: Push 'thingsboard-http-transport' Image to Docker Registry
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-http-transport:$IMAGE_VERSION

    - name: Push 'thingsboard-mqtt-transport' Image to Docker Registry
    run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-mqtt-transport:$IMAGE_VERSION

    - name: Push 'thingsboard-js-executor' Image to Docker Registry
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-js-executor:$IMAGE_VERSION

    - name: Push 'thingsboard-web-ui' Image to Docker Registry
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/thingsboard-web-ui:$IMAGE_VERSION
