name: Docker Image Build

on:
  push:
    branches:
      - main

  repository_dispatch:

  workflow_dispatch:
    inputs:
      cleanup:
        type: boolean
        description: 'Clean up build environment for additional disk space'
        required: false
        default: true

      debug:
        type: boolean
        description: 'Enable debug mode'
        required: false
        default: false

env:
  IMAGE_REGISTRY: docker.pkg.github.com
  IMAGE_REPOSITORY: valuabletouch/thingsboard
  IMAGE_VERSION: build-${{ github.run_number }}
  THINGSBOARD_GIT_REPO: https://github.com/valuabletouch/thingsboard.git
  THINGSBOARD_GIT_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check current path
      run: pwd

    - name: Print Docker information
      run: docker info

    - name: Check disk spaces before clean up
      if: ${{ inputs.debug }}
      run: sudo df -hlT /

    - name: List 100 largest packages before clean up
      if: ${{ inputs.debug }}
      run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head -n 100

    - name: Ensure apt-fast is installed
      if: ${{ inputs.cleanup }}
      run: |
        sudo add-apt-repository ppa:apt-fast/stable
        sudo apt-get update
        sudo apt-get -y install apt-fast

    - name: Clean up build environment for additional disk space
      if: ${{ inputs.cleanup }}
      uses: rokibhasansagar/slimhub_actions@main
      with:
          retain: "docker_buildkit"

    - name: List 100 largest packages after clean up
      if: ${{ inputs.debug }}
      run: dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -nr | head -n 100

    - name: Check disk spaces after clean up
      if: ${{ inputs.debug }}
      run: sudo df -hlT /

    - name: Checkout files
      uses: actions/checkout@v2

    - name: Build 'ThingsBoard Base Java' Docker Image
      run: |
        docker build \
            --file Dockerfile.base-java \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/base/java:latest \
            .

    - name: Build 'ThingsBoard Base JavaScript' Docker Image
      run: |
        docker build \
            --file Dockerfile.base-js \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/base/js:latest \
            .

    - name: Build 'ThingsBoard Build Intermediate' Docker Image
      run: |
        docker build \
            --file Dockerfile.build \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/build:$IMAGE_VERSION \
            --build-arg THINGSBOARD_GIT_REPO=$THINGSBOARD_GIT_REPO \
            --build-arg THINGSBOARD_GIT_BRANCH=$THINGSBOARD_GIT_BRANCH \
            .

    - name: Build 'ThingsBoard Node Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.node \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/node:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/node:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard Monitoring Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.monitoring \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/monitoring:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/monitoring:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard COAP Transport Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.coap-transport \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/coap-transport:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/coap-transport:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard HTTP Transport Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.http-transport \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/http-transport:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/http-transport:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard LWM2M Transport Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.lwm2m-transport \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/lwm2m-transport:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/lwm2m-transport:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard MQTT Transport Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.mqtt-transport \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/mqtt-transport:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/mqtt-transport:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard SNMP Transport Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.snmp-transport \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/snmp-transport:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/snmp-transport:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard Version Control Executor Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.vc-executor \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/vc-executor:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/vc-executor:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard JavaScript Executor Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.js-executor \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/js-executor:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/js-executor:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Build 'ThingsBoard Web UI Microservice' Docker Image
      run: |
        docker build \
            --file Dockerfile.web-ui \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/web-ui:latest \
            --tag $IMAGE_REGISTRY/$IMAGE_REPOSITORY/web-ui:$IMAGE_VERSION \
            --build-arg IMAGE_REPOSITORY=$IMAGE_REGISTRY/$IMAGE_REPOSITORY \
            --build-arg IMAGE_VERSION=$IMAGE_VERSION \
            .

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PUSH_PACKAGE_PAT }}

    - name: Push 'ThingsBoard Node Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/node:latest

    - name: Push 'ThingsBoard Node Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/node:$IMAGE_VERSION

    - name: Push 'ThingsBoard Monitoring Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/monitoring:latest

    - name: Push 'ThingsBoard Monitoring Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/monitoring:$IMAGE_VERSION

    - name: Push 'ThingsBoard COAP Transport Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/coap-transport:latest

    - name: Push 'ThingsBoard COAP Transport Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/coap-transport:$IMAGE_VERSION

    - name: Push 'ThingsBoard HTTP Transport Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/http-transport:latest

    - name: Push 'ThingsBoard HTTP Transport Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/http-transport:$IMAGE_VERSION

    - name: Push 'ThingsBoard LWM2M Transport Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/lwm2m-transport:latest

    - name: Push 'ThingsBoard LWM2M Transport Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/lwm2m-transport:$IMAGE_VERSION

    - name: Push 'ThingsBoard MQTT Transport Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/mqtt-transport:latest

    - name: Push 'ThingsBoard MQTT Transport Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/mqtt-transport:$IMAGE_VERSION

    - name: Push 'ThingsBoard SNMP Transport Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/snmp-transport:latest

    - name: Push 'ThingsBoard SNMP Transport Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/snmp-transport:$IMAGE_VERSION

    - name: Push 'ThingsBoard Version Control Executor Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/vc-executor:latest

    - name: Push 'ThingsBoard Version Control Executor Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/vc-executor:$IMAGE_VERSION

    - name: Push 'ThingsBoard JavaScript Executor Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/js-executor:latest

    - name: Push 'ThingsBoard JavaScript Executor Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/js-executor:$IMAGE_VERSION

    - name: Push 'ThingsBoard Web UI Microservice' Image to Docker Registry (latest)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/web-ui:latest

    - name: Push 'ThingsBoard Web UI Microservice' Image to Docker Registry (build)
      run: docker push $IMAGE_REGISTRY/$IMAGE_REPOSITORY/web-ui:$IMAGE_VERSION

    - name: Trigger Webhook
      run: |
        curl \
          --location \
          --request POST '${{ secrets.BUILD_WEBHOOK_URL }}' \
          --header 'Authorization: ${{ secrets.BUILD_WEBHOOK_AUTHORIZATION }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{"variables":{"ThingsBoard.ImageTag":{"isSecret":false,"value":"${{ env.IMAGE_VERSION }}"}}}'

    - name: Check disk spaces after build
      if: ${{ inputs.debug && !cancelled() }}
      run: sudo df -h